### ISSUE TITLE
resolution option is not working 

### ISSUE THREAD

**Issue by kevin-8387** [Lukasss93/pdf-to-ppm#1]
Hi,
The resolution Option is not working as you use (+) operator for merging the array
![image](https://user-images.githubusercontent.com/6768026/171403989-183c1fb1-96a3-4a49-9a86-7583aca0de39.png)
as when $a = $a + $b; // Union of $a and $b so the index of 0 and 1 of $b array were replaced by the index of $a in our case replaced by pdf file and path

**Comment by Lukasss93** [comment]
Fixed in https://github.com/Lukasss93/pdf-to-ppm/releases/tag/v1.0.2

**Comment by kevin-8387** [comment]
> Fixed in https://github.com/Lukasss93/pdf-to-ppm/releases/tag/v1.0.2

great (y)
